// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnkajdtceeldthdsbsth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZua2FqZHRjZWVsZHRoZHNic3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDIxMzUsImV4cCI6MjA2NjYxODEzNX0.V-bE1JYUwW2ZsM3wi55LHCLxCqMtrvJZxPhOpK_h9k4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);